### ISSUE TITLE
Question about Pharo integration

### ISSUE THREAD

**Issue by amiracam** [fuhrmanator/PlantUMLPharoGizmo#10]
Sorry, but is there a way of using it in Pharo without Moose ? i.e. to the extent that there's a text pane where PlantUML syntax can be entered and a second pane that in a REPL manner shows the corresponding UML diagram ? 

thanks

**Comment by fuhrmanator** [comment]
Hello and sorry for the late reply. Today I created a fork https://github.com/fuhrmanator/PlantUMLPharoGizmo/tree/pharo9 that should not have any need for Moose. It's working for Pharo 9. You need to load it via 

```smalltalk
Metacello new
  repository: 'github://fuhrmanator/PlantUMLPharoGizmo:pharo9/src';
  baseline: 'PUGizmo';
  load.
```

Then you can open with `PUGizmo open` in a playground. I hope this works for you.

**Comment by fuhrmanator** [comment]
Also, if you just want core PlantUML support, check out https://github.com/kasperosterbye/PlantUMLBridge if you didn't already know about it.
