### ISSUE TITLE
Impossibility to print inheritances from a FASTPharo model

### ISSUE THREAD

**Issue by enwiro** [fuhrmanator/PlantUMLPharoGizmo#13]
The impossibility to print inheritances from a FASTPharo model comes from the fact that the FamixStClass of the FASTPharo model have a SmalltalkContainer type.

![image](https://user-images.githubusercontent.com/58632394/117977013-ae5c0380-b330-11eb-94d2-f8495a4ba19e.png)

In other words, it is not possible for this FamixStClass to understand isInterface because this concept does not exist in this language.

**Comment by enwiro** [comment]
I'm on it.

**Comment by fuhrmanator** [comment]
fixed in #15
