### ISSUE TITLE
URLs from large source files won't render on www.plantuml.com

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/PlantUMLPharoGizmo#2]
When using long-ish source files, a URL is produced that won't render on plantuml.com's web engine. For example:

https://www.plantuml.com/plantuml/img/SoWkIImgAStDuKtKjKjIi5B8ICt9oHyOZhf7Qb6gUh52ea9oVcvkQbx9o1SP-I8ZNsJaYunG4OVKl1HWoGm0

Although I'm not able to say precisely why this happens, after spending some time, here are the details I uncovered:

- Using the URL above, I see that there is no error from www.plantuml.com, yet nothing is returned. Chrome's developer tools shows the response code is 200 and the content size is 0. This response is problematic to process in PlantUMLPharoGizmo for obvious reasons.
- Digging into the details, I found that the ZLib (deflate) compression used by Pharo in its `ZLibWriteStream` is `FLEVEL=1`, which is not the default (`FLEVEL=2`) and appears to be hard-coded to that level. The headers are set with the method:
    ```Smalltalk
    writeHeader
        "Write header information"
        encoder nextBits: 8 put: 120. "deflate method with 15bit window size"
        encoder nextBits: 8 put: 94. "checksum; no preset; fast (flevel=1) compression"
    ```
    Digging into the Pharo sources of the VM with some colleagues at RMoD showed that the code is a VM plug-in that was written in 1999. Perhaps FLEVEL=1 was chosen because a modern ZLib wasn't available and it was simpler to code only the "fast" implementation.  
- Running [PlantUML's server](https://github.com/plantuml/plantuml-server) on `localhost` allows these URLs to render, suggesting it's a bug in the www.plantuml.com's server. Perhaps the FLEVEL=1 encoding is tripping up the particular decoder there?
- Using the localhost implementation of the server, I wrote some SUnit tests in Pharo that take the source code and generate a PlantUML key, then invoke the `/uml/` option of the URL on the server to get the source code back in a `<textfield>` of the contents page. Here's a snippet from `StringTest` extension `testPlantUMLLocalhostRandom`:
    ```smalltalk
    "Use the plantuml/uml endpoint to get the source back from the key"
        recoveredSource := self sourceFromLocalhost: source asPlantUMLKey.
        self assert: source equals: recoveredSource asCRfromLF
    ```

**Comment by fuhrmanator** [comment]
It appears this issue was cleared up on PlantUML.com's server. Closing this.

**Comment by macta** [comment]
Does this mean your warning in the initial project readme can now be removed? i was a bit put off trying it if I had to download a server of my own... so its great news if its not an issue

**Comment by fuhrmanator** [comment]
Yes, I will remove the warning.
