### ISSUE TITLE
Something seems wrong with the baseline

### ISSUE THREAD

**Issue by kasperosterbye** [fuhrmanator/PlantUMLPharoGizmo#8]
When I try to load the PUGizmo baseline I get this error. This is on Pharo8, fresh image as of 2019-11-22.

```Smalltalk
Metacello new
  repository: 'github://fuhrmanator/PlantUMLPharoGizmo/src';
  baseline: 'PUGizmo';
  load.
```

<img width="582" alt="image" src="https://user-images.githubusercontent.com/17723745/69403985-4f4d9d80-0cfc-11ea-87ef-b56b5f9b08c9.png">

**Comment by fuhrmanator** [comment]
Thanks @kasperosterbye for reporting this.

I think the latest baseline is expecting Moose in the Image (that would explain the Famix* problems). I need to fix the baseline to not load the PUGizmo stuff for moose if it's not present.

Another issue is that Pharo 8 renamed ZnUrlTests to ZnUrlTest, and it breaks my extension with tests of ZnUrl#isValid. 

Are you at least able to use the code?

**Comment by kasperosterbye** [comment]
The only thing I needed to use was the "load a plantuml image from a plantuml source text". I was able to pick that out of the extensions in String. So yes, I got what I needed - very helpful indeed.
I will need to credit you for that part, but there is no licence in your code, so I guess it is fine to just credit you in some appropriate comment somewhere before I push what I am working on.

**Comment by fuhrmanator** [comment]
Oops. License added! Thanks for letting me know. This was started in a Pharo sprint, and I missed a few things.

**Comment by kasperosterbye** [comment]
Interesting. I think Pharo and Moose use the MIT licence. But you are of cause free to pick the licence you like.

**Comment by fuhrmanator** [comment]
See https://github.com/fuhrmanator/PlantUMLPharoGizmo/issues/17#issuecomment-955024063
